# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 				Lijing Shao
institute:    KIAA, Beijing China
email: 				lshao@pku.edu.cn
visit:        <a href="https://hits.seeyoufarm.com"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Ffriendshao.github.io&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=今/总访问量&edge_flat=false"/></a>
encoding:			utf-8

description: > # this means to ignore newlines until "baseurl:"
  <b>Occam-Einstein Razor</b> <p>Physics should be as simple as possible, but not simpler.</p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://friendshao.github.io" # the base hostname & protocol for your site
# facebook_username: Friendshao
# twitter_username: Friendshao
# github_username:  Friendshao
# bitbucket_username: Friendshao
# Build settings
markdown: kramdown
